### ISSUE TITLE
It works on IE10, but the style is not right.

### ISSUE THREAD

**Issue by hjzheng** [disjukr/input-range-polyfill#1]
Try your example, I found the input style is not right, can you have plan to fix it.
![ie10](https://cloud.githubusercontent.com/assets/4166657/6507087/a77d33c8-c38a-11e4-8615-878c1b904c28.png)

**Comment by disjukr** [comment]
its not bug. this is internet explorer's default style.
the purpose of this library is just make `input[type=range]` to work.
